In [1]:
import numpy as np

def is_diagonally_dominant(matrix):
    mat = np.array(matrix)
    n = mat.shape[0]
    
    for i in range(n):
        # Find the absolute value of the diagonal element
        diag_val = abs(mat[i, i])
        
        # Calculate the sum of absolute values of all other elements in the row
        row_sum = np.sum(np.abs(mat[i, :])) - diag_val
        
        # If the diagonal is not strictly greater than the sum, it fails the test
        if diag_val <= row_sum:
            return False
            
    return True

def evaluate_and_display(matrix):
    result = is_diagonally_dominant(matrix)
    print(f"Is the matrix diagonally dominant? {result}")
    print(np.array(matrix))
    print()

# --- Test Cases ---

# Test Matrix 1: A strictly diagonally dominant matrix
matrix_1 = [
    [4, 1, -1],
    [2, 7, 1],
    [1, -3, 12]
]

# Test Matrix 2: Another strictly diagonally dominant matrix
matrix_2 = [
    [10, -2, -1, -1],
    [-2, 10, -1, -1],
    [-1, -1, 10, -2],
    [-1, -1, -2, 10]
]

# Run the evaluations to match the requested output format
evaluate_and_display(matrix_1)
evaluate_and_display(matrix_2)

Is the matrix diagonally dominant? True
[[ 4  1 -1]
 [ 2  7  1]
 [ 1 -3 12]]

Is the matrix diagonally dominant? True
[[10 -2 -1 -1]
 [-2 10 -1 -1]
 [-1 -1 10 -2]
 [-1 -1 -2 10]]

